---
# Defines deployment design and assigns role to server groups

- hosts: all
  sudo: True
  roles:
  - common

- hosts: mons
  sudo: True
  roles:
  - mon

- hosts: osds
  sudo: True
  roles:
  - osd
  - mds
